---
environments:
  default:
    values:
      - ./environments/default.yaml.gotmpl
    secrets:
      - ./environments/default.secrets.yaml
  production:
    values:
      - ./environments/production.yaml.gotmpl
    secrets:
      - ./environments/production.secrets.yaml
---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    values:
    - ./values/prometheus.yaml.gotmpl